version: "3.7"

volumes:
  gradle_user_home:
  vs_code_server:

services:
  demo:
    image: vovimayhem/spring-demo:development
    build:
      context: .
      # target: development
    ports:
      - ${DEMO_WEB_PORT:-8080}:8080
    volumes:
      - .:/usr/src
      - gradle_user_home:/usr/local/gradle
      - vs_code_server:/usr/src/.vscode-server
    depends_on:
      - postgres

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    stdin_open: true
    tty: true

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo_development
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3x4mpl3P455w0rd
