name: CI & CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_build:
    name: Build Test Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Add CI/CD scripts to system path
        run: echo "::add-path::${GITHUB_WORKSPACE}/.github/workflows/bin"

      - name: Login to Github Package Registry for Docker
        run: docker login docker.pkg.github.com -u vovimayhem --password ${{ secrets.GITHUB_TOKEN }}

      - name: Build Test Image
        run: ci-compose build test

      - name: Push Test Image
        run: ci-compose push test

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [test_build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Add CI/CD scripts to system path
        run: echo "::add-path::${GITHUB_WORKSPACE}/.github/workflows/bin"

      - name: Login to Github Package Registry for Docker
        run: docker login docker.pkg.github.com -u vovimayhem --password ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Test Image
        run: ci-compose pull test

      - name: Run tests
        run: ci-compose run test gradle test

  release_build:
    name: Build Release Image
    runs-on: ubuntu-latest
    needs: [test_build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Add CI/CD scripts to system path
        run: echo "::add-path::${GITHUB_WORKSPACE}/.github/workflows/bin"

      - name: Login to Github Package Registry for Docker
        run: docker login docker.pkg.github.com -u vovimayhem --password ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Test Image
        run: ci-compose pull test

      - name: Build Builder Image
        run: ci-compose build builder

      - name: Build Release Image
        run: ci-compose build release

      - name: Push the Release Image
        run: ci-compose push release

